name: Run AHA Recommendation Script

on:
  schedule:
    - cron: '30 16 * * *'  # 10:30 PM IST daily
  workflow_dispatch:        # Manual trigger support

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          mkdir -p credentials
          echo "$GOOGLE_CREDENTIALS" > credentials/client_secret.json
          python main.py
